on: [push]

jobs:
  encode:
    runs-on: ubuntu-latest
    name: Encode
    steps:
      - uses: actions/checkout@v3
      - name: Encode
        uses: adawesomeguy/w3strings-action@v1.1
        with:
          csv-path: 'en.w3strings.csv'
          id-space: 6720
          out-dir: 'w3strings'
          language: 'en'
      - uses: endbug/add-and-commit@v8
        with:
            default_author: github_actions
            message: 'Update W3Strings'
